"""
DPO Phase 2: Train on pre-generated preference pairs.
Pairs already generated by vLLM in /workspace/dpo_pairs.jsonl
"""
import os, sys, json, zipfile
import torch

os.environ["WANDB_API_KEY"] = "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"
import wandb
wandb.login(key=os.environ["WANDB_API_KEY"])

from peft import LoraConfig, PeftModel, TaskType
from transformers import AutoModelForCausalLM, AutoTokenizer
from trl import DPOTrainer, DPOConfig
from datasets import Dataset as HFDataset

MODEL_PATH = "nvidia/NVIDIA-Nemotron-3-Nano-30B-A3B-BF16"
ADAPTER_PATH = "/workspace/workspace/sft_adapter"

# Load DPO pairs
dpo_data = []
with open("/workspace/dpo_pairs.jsonl") as f:
    for line in f:
        dpo_data.append(json.loads(line))
print(f"Loaded {len(dpo_data)} DPO pairs")

# Load model + merge SFT adapter
print("Loading model...")
model = AutoModelForCausalLM.from_pretrained(
    MODEL_PATH, device_map="auto", trust_remote_code=True, dtype=torch.bfloat16
)
tokenizer = AutoTokenizer.from_pretrained(MODEL_PATH, trust_remote_code=True)
if tokenizer.pad_token is None:
    tokenizer.pad_token = tokenizer.eos_token
tokenizer.padding_side = "left"
print("Model loaded")

if os.path.exists(os.path.join(ADAPTER_PATH, "adapter_config.json")):
    print("Merging SFT adapter...")
    model = PeftModel.from_pretrained(model, ADAPTER_PATH)
    model = model.merge_and_unload()
    print("Merged")

dataset = HFDataset.from_list(dpo_data)

lora_config = LoraConfig(
    r=32, lora_alpha=64,
    target_modules=r".*\.(in_proj|out_proj|up_proj|down_proj)$",
    lora_dropout=0.05, bias="none", task_type=TaskType.CAUSAL_LM,
)

training_args = DPOConfig(
    output_dir="/workspace/dpo_output",
    num_train_epochs=2,
    per_device_train_batch_size=1,
    gradient_accumulation_steps=4,
    learning_rate=5e-7,
    beta=0.1,
    loss_type="sigmoid",
    warmup_steps=5,
    lr_scheduler_type="cosine",
    logging_steps=1,
    save_strategy="epoch",
    bf16=True,
    gradient_checkpointing=True,
    gradient_checkpointing_kwargs={"use_reentrant": False},
    report_to="wandb",
    run_name="dpo-v1-on-sft-v8",
    remove_unused_columns=False,
    max_length=4096,
    max_prompt_length=2048,
)

wandb.init(project="nemotron-reasoning", name="dpo-v1-on-sft-v8",
    config={"method": "DPO", "base": "sft-v8", "lr": 5e-7,
            "beta": 0.1, "epochs": 2, "pairs": len(dpo_data)},
    tags=["dpo", "on-sft-v8"])

trainer = DPOTrainer(
    model=model,
    args=training_args,
    train_dataset=dataset,
    processing_class=tokenizer,
    peft_config=lora_config,
)

print(f"Starting DPO: 2 epochs, {len(dpo_data)} pairs")
trainer.train()
print("DPO complete!")

OUTPUT_DIR = "/workspace/dpo_adapter"
os.makedirs(OUTPUT_DIR, exist_ok=True)
trainer.save_model(OUTPUT_DIR)

zip_path = "/workspace/submission.zip"
with zipfile.ZipFile(zip_path, 'w', zipfile.ZIP_STORED) as zf:
    for fname in os.listdir(OUTPUT_DIR):
        fpath = os.path.join(OUTPUT_DIR, fname)
        if os.path.isfile(fpath):
            zf.write(fpath, fname)
print(f"submission.zip: {os.path.getsize(zip_path)/1024/1024:.1f} MB")
wandb.finish()
print("DONE")
